"""Initial version

Revision ID: 376f179daa2d
Revises: 
Create Date: 2023-02-16 21:36:29.548952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376f179daa2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('requiredDonations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_id'), 'reward', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('donor', 'organization', name='usertype'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('donationCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('condition', sa.Enum('new', 'veryGood', 'good', 'acceptable', name='objectcondition'), nullable=False),
    sa.Column('category', sa.Enum('clothing', 'electronics', 'household', 'toys', 'media', 'sport', 'school', 'personal', name='objectcategory'), nullable=False),
    sa.Column('status', sa.Enum('reserved', 'donated', 'available', name='objectstatus'), nullable=False),
    sa.Column('donorId', sa.Integer(), nullable=False),
    sa.Column('organizationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donorId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_id'), 'object', ['id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewerId', sa.Integer(), nullable=False),
    sa.Column('reviewedId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reviewedId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_table('reward_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('rewardId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rewardId'], ['reward.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_allocation_id'), 'reward_allocation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_allocation_id'), table_name='reward_allocation')
    op.drop_table('reward_allocation')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_object_id'), table_name='object')
    op.drop_table('object')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_reward_id'), table_name='reward')
    op.drop_table('reward')
    # ### end Alembic commands ###
