"""autoincrement pks

Revision ID: 4946806e0cf7
Revises: 376f179daa2d
Create Date: 2023-02-18 16:45:35.712427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4946806e0cf7'
down_revision = '376f179daa2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reviewerId', sa.Integer(), nullable=False),
    sa.Column('reviewedId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['reviewedId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.drop_index('ix_rating_id', table_name='rating')
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reviewerId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewedId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reviewedId'], ['user.id'], name='rating_reviewedId_fkey'),
    sa.ForeignKeyConstraint(['reviewerId'], ['user.id'], name='rating_reviewerId_fkey'),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    op.create_index('ix_rating_id', 'rating', ['id'], unique=False)
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
