"""New column to user & allocation

Revision ID: d69e85281ca8
Revises: 4946806e0cf7
Create Date: 2023-02-25 16:31:37.105928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69e85281ca8'
down_revision = '4946806e0cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_allocation', sa.Column('acquireDate', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('reviewCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reviewCount')
    op.drop_column('reward_allocation', 'acquireDate')
    # ### end Alembic commands ###
