"""images

Revision ID: ec277348887e
Revises: f2532c8a2a5a
Create Date: 2023-05-25 22:10:27.177776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec277348887e'
down_revision = 'f2532c8a2a5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('objectId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objectId'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.add_column('user', sa.Column('rewardCount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('profile_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_url')
    op.drop_column('user', 'rewardCount')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
