"""date to objects

Revision ID: f2e4c4d1f684
Revises: ec277348887e
Create Date: 2023-06-13 21:57:05.256112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e4c4d1f684'
down_revision = 'ec277348887e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'date')
    # ### end Alembic commands ###
